# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blorejobs',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chennaijobs',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hydjobs',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punejobs',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
